[project]
name = "crypto-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bip-utils>=2.9.3",
    "eth-account>=0.13.7",
    "pydantic>=2.11.4",
    "pyyaml>=6.0.2",
    "typer>=0.15.4",
    "web3>=7.11.1",
]
